### ISSUE TITLE
Start Button push to google maps route

### ISSUE THREAD

**Issue by nitro56565** [nitro56565/life-matters#21]
On clicking start button the 2 (source and destination) points needs to be fetched and send to google maps route where we generally start a trip. 
Edge Case - if there is no source or destination then the trip should not start and should give a message to input both source and destination before starting the trip.
![image](https://github.com/user-attachments/assets/d8cdc96c-93db-4299-a385-6a8ccfe83182)

**Comment by w2wewwww** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by SamikshaKadam19** [comment]
Working on it
