### ISSUE TITLE
Current Location Logo Fix

### ISSUE THREAD

**Issue by nitro56565** [nitro56565/life-matters#23]
Currently the 'Current Location' button contains a svg link is should be replaced by the local image which is present in the assets folder of the directory

**Comment by shaalan-ahmed** [comment]
### HI, i am interested in fixing the issue!  
Where is the "Current Location" button instantiated so i can get started?

**Comment by shaalan-ahmed** [comment]
I think i found it, i will address this issue ASAP

**Comment by nitro56565** [comment]
start with forking and cloning this repo and then you will find a pages folder inside src there we have a page named ambulance-main-page there you will find the current location button which needs to be fixed also please make sure it is properly aligned

**Comment by nitro56565** [comment]
> I think i found it, i will address this issue ASAP

thats good make sure to use ("git commit -s -m 'message' " )  -s for signoff when committing the code

**Comment by shaalan-ahmed** [comment]
I don't think i used "-s" in the commit command

**Comment by LucioPalmucci** [comment]
Assign it to me @nitro56565
