### ISSUE TITLE
(Mobile) Single finger scroll allow on google map

### ISSUE THREAD

**Issue by nitro56565** [nitro56565/life-matters#24]
When we try to scroll around on google maps (integrated on our website) it says 'use 2 fingers to move the map'. We should be able to move the map with one finger scroll as well.
![maps-issue](https://github.com/user-attachments/assets/c090d83b-83b3-4b26-bf63-c8f5719403c7)

**Comment by SamikshaKadam19** [comment]
Working on it

**Comment by nitro56565** [comment]
hey @SamikshaKadam19 this issue is not yet resolved please look into it again

**Comment by SamikshaKadam19** [comment]
Looking into it

**Comment by SamikshaKadam19** [comment]
@nitro56565 It seems to be resolved now

**Comment by nitro56565** [comment]
Resolved #40
