### ISSUE TITLE
Make Login page work with DB with JWT

### ISSUE THREAD

**Issue by nitro56565** [nitro56565/life-matters#31]
Implement Login functionality where we will authorize on the basis of MongoDB data and authenticate using JWT

**Comment by ChaudaryHammad** [comment]
I have reviewed your backend code it lacks proper modularity. Is it not required or you left it intentionally? Secondly, what sort of login functionality is required an explanation can be helpful as I am willing to contribute.

**Comment by nitro56565** [comment]
Hey @ChaudaryHammad yes I have left it intentionally because I was working on the Ambulance portal and had to hold the login page integration , if you need more detail I would love to invite you on our discord where we discuss about the backend code if that works with you

**Comment by ChaudaryHammad** [comment]
Send me the invite link, and we can dive deeper into the details.

**Comment by nitro56565** [comment]
sure, https://discord.gg/nuNgRzDg
