### ISSUE TITLE
Create a forgot password page UI 

### ISSUE THREAD

**Issue by nitro56565** [nitro56565/life-matters#36]
Need to create a UI for forgot password page where we would verify on the basis of mobile OTP so we need only mobile number as input on forgot password page (need to create a new component which should match with out design)

**Comment by surajb0710** [comment]
Will pick this up tom, if you have any design ready, please share or I will follow the signin form design.

**Comment by nitro56565** [comment]
@surajb0710 I don't have a design you can follow up with sign in design, I'll assign the task as well

**Comment by nitro56565** [comment]
Resolved
