### ISSUE TITLE
Home Component page scroll issue

### ISSUE THREAD

**Issue by nitro56565** [nitro56565/life-matters#38]
Home Component x axis and y axis scroll is there need to fix that

**Comment by nitro56565** [comment]
@ChaudaryHammad I have assigned it to you

**Comment by ChaudaryHammad** [comment]
![Screenshot 2024-09-09 211358](https://github.com/user-attachments/assets/035d081a-9cb6-4fda-8fec-827c8cf726fd)
![Screenshot 2024-09-09 211346](https://github.com/user-attachments/assets/0c66228b-0d40-45e2-8589-58673055c516)
it's done i am creating a PR shortly.

**Comment by nitro56565** [comment]
thats good, make sure its works properly on responsiveness as well

**Comment by nitro56565** [comment]
hey @ChaudaryHammad your code is working fine but the overflow hidden property in index.css is creating issue for google maps to load on ambulance-home route can you please check that (make sure to pull i have made some changes)

**Comment by nitro56565** [comment]
Scroll issue fixed for now will need more amendments in react native platform
